study:
  accession: OSD-47
  organism: Mus musculus

input_dir: /Volumes/bryan_SSD/genelab
metadata_file: null

trimming:
  enabled: true
  tool: fastp
  adapter_sequence: null
  qualified_quality_phred: 20
  unqualified_percent_limit: 30
  min_length: 20
  cut_right: false
  cut_window_size: 4
  cut_mean_quality: 20
  poly_x: false
  poly_x_min_len: 10
  threads: 4

alignment:
  enabled: true
  tool: hisat2
  hisat2_index_base: results/hisat2_index/workspace/ensembl_112/Mus_musculus.GRCm39.dna.primary_assembly
  rna_strandness: R
  threads: 8
  sort_threads: 4

feature_counts:
  enabled: true
  tool: featureCounts
  gtf: refs/ensembl_112/Mus_musculus.GRCm39.112.gtf
  strandedness: 2
  feature_type: exon
  attribute_type: gene_id
  threads: 8
  output: results/counts/osd47_featureCounts.txt

archives:
  - id: C-Ba-1
    file: GLDS-47_rna-seq_C-Ba-1.tar.gz
    condition: BSL
    replicate: 1
  - id: C-Ba-2
    file: GLDS-47_rna-seq_C-Ba-2.tar.gz
    condition: BSL
    replicate: 2
  - id: C-Ba-3
    file: GLDS-47_rna-seq_C-Ba-3.tar.gz
    condition: BSL
    replicate: 3
  - id: C-FLT-1
    file: GLDS-47_rna-seq_C-FLT-1.tar.gz
    condition: FLT
    replicate: 1
  - id: C-FLT-2
    file: GLDS-47_rna-seq_C-FLT-2.tar.gz
    condition: FLT
    replicate: 2
  - id: C-FLT-4
    file: GLDS-47_rna-seq_C-FLT-4.tar.gz
    condition: FLT
    replicate: 4
  - id: C-GC-2
    file: GLDS-47_rna-seq_C-GC-2.tar.gz
    condition: GC
    replicate: 2
  - id: C-GC-3
    file: GLDS-47_rna-seq_C-GC-3.tar.gz
    condition: GC
    replicate: 3
  - id: C-GC-5
    file: GLDS-47_rna-seq_C-GC-5.tar.gz
    condition: GC
    replicate: 5

outputs:
  archive_manifest: results/metadata/archive_manifest.tsv
  lane_manifest: results/metadata/lane_manifest.tsv